name: CI

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.4.0
        with:
          go-version-file: go.mod
          cache: true

      - name: gofmt
        run: |
          files=$(gofmt -s -l .)
          if [ -n "$files" ]; then
            echo "gofmt found unformatted files:"
            echo "$files"
            exit 1
          fi

      - name: go mod tidy
        run: go mod tidy && git diff --no-patch --exit-code go.mod go.sum

      - name: go vet
        run: go vet ./...

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.4.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Install goversioninfo
        run: go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest

      - name: go generate
        run: go generate

      - name: go test
        run: go test ./...

      - name: go build
        shell: pwsh
        run: go build -ldflags "-H=windowsgui -s -w" -o snapflow.exe .

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: snapflow-dev
          path: snapflow.exe
          retention-days: 7
